name: Despliegue en Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login a Docker Hub
        run: docker login docker.io -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Descargar imagen desde Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/holaMundo4:latest

      - name: Renombrar imagen para Heroku
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/holaMundo4:latest registry.heroku.com/holamundo4/web

      - name: Login al Heroku Container Registry
        run: |
          echo "HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}"
          heroku container:login -a holamundo4
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Subir imagen a Heroku
        run: |
          docker push registry.heroku.com/holamundo4/web

      - name: Redesplegar en Heroku
        run: |
          heroku container:release web -a holamundo4
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}