name: Deploy a Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Descargar Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh  | sh

      - name: Iniciar sesión en Heroku
        run: |
          heroku auth:token:set ${{ secrets.HEROKU_API_KEY }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Configurar remote de Heroku
        run: |
          heroku git:remote -a holamundo4

      - name: Subir y desplegar en Heroku
        run: |
          git push heroku main