name: Despliegue en Heroku desde Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login en Heroku Container Registry
        run: |
          docker login registry.heroku.com --username=_ --password=${{ secrets.HEROKU_API_KEY }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Login en Docker Hub
        run: |
          docker login docker.io -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Descargar imagen desde Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/holaMundo4:latest

      - name: Etiquetar imagen para Heroku
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/holaMundo4:latest registry.heroku.com/tu-app-heroku/web

      - name: Subir imagen a Heroku
        run: |
          docker push registry.heroku.com/tu-app-heroku/web

      - name: Redesplegar en Heroku
        run: |
          APP_NAME=holamundo4
          curl -n -X PATCH https://api.heroku.com/apps/ $APP_NAME/formation \
            -d '{
              "updates": [
                {
                  "type": "web",
                  "docker_image": "$(docker inspect registry.heroku.com/$APP_NAME/web | jq -r '.[0].RepoDigests[0]' | cut -d "@" -f 2)"
                }
              ]
            }' \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-reformation"
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          