name: Despliegue en Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh  | sh

      - name: Verificar instalación
        run: heroku --version

      - name: Iniciar sesión en Heroku
        run: |
          # Autenticar con token
          heroku auth:token:set ${{ secrets.HEROKU_API_KEY }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Eliminar remote heroku si existe
        run: |
          git remote remove heroku || echo "No había remote heroku"

      - name: Configurar remote de Heroku manualmente
        run: |
          # Configurar remote usando la URL correcta
          git remote add heroku https://git.heroku.com/holamundo4.git 

      - name: Hacer commit vacío para forzar deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Forzar deploy a Heroku"

      - name: Desplegar en Heroku
        run: |
          # Agregar credenciales al push
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/holamundo4.git main