name: Despliegue en Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh  | sh

      - name: Verificar instalación
        run: heroku --version

      - name: Iniciar sesión en Heroku
        run: |
          # Usar el API KEY para autenticar
          heroku auth:token:set ${{ secrets.HEROKU_API_KEY }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Configurar remote de Heroku (oficial)
        run: |
          # Eliminar remote heroku si existe
          git remote remove heroku || echo "No había remote heroku"

          # Crear el remote usando el CLI de Heroku
          heroku git:remote -a holaMundo4
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Hacer commit vacío para forzar deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Forzar deploy a Heroku"

      - name: Desplegar en Heroku
        run: |
          git push heroku main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}