name: Deploy to Heroku with Docker

on:
  push:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/holamundo4:latest

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh  | sh
          heroku --version

      - name: Ensure container stack
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku stack:set container -a holamundo4

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Pull image from DockerHub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/holamundo4:latest

      - name: Tag and Push to Heroku
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/holamundo4:latest registry.heroku.com/holamundo4/web
          docker push registry.heroku.com/holamundo4/web

      - name: Release on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web --app holamundo4